# permissions for end users to view externalconfigmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalconfigmap-viewer-role
rules:
- apiGroups:
  - external-secrets-operator.slamdev.net
  resources:
  - externalconfigmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - external-secrets-operator.slamdev.net
  resources:
  - externalconfigmaps/status
  verbs:
  - get
