# permissions for end users to view externalsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalsecret-viewer-role
rules:
- apiGroups:
  - external-secrets-operator.slamdev.net
  resources:
  - externalsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - external-secrets-operator.slamdev.net
  resources:
  - externalsecrets/status
  verbs:
  - get
