---
apiVersion: external-secrets-operator.slamdev.net/v1alpha1
kind: ExternalBackend
metadata:
  name: consul-prod
spec:
  type: Consul
  secretName: consul-prod-backend
---
apiVersion: v1
kind: Secret
metadata:
  name: consul-prod-backend
type: Opaque
stringData:
  httpAddr: 'http://consul.consul-prod'
  httpToken: 'some-token'

---
apiVersion: external-secrets-operator.slamdev.net/v1alpha1
kind: ExternalBackend
metadata:
  name: consul-dev
spec:
  type: Consul
  secretName: consul-dev-backend
---
apiVersion: v1
kind: Secret
metadata:
  name: consul-dev-backend
type: Opaque
stringData:
  httpAddr: 'http://consul.consul-dev'

---
apiVersion: external-secrets-operator.slamdev.net/v1alpha1
kind: ExternalBackend
metadata:
  name: vault-prod
spec:
  type: Vault
  secretName: vault-prod-backend
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-prod-backend
type: Opaque
stringData:
  addr: 'http://vault.vault-prod'
  token: 'some-token'

---
apiVersion: external-secrets-operator.slamdev.net/v1alpha1
kind: ExternalBackend
metadata:
  name: vault-dev
spec:
  type: Vault
  secretName: vault-dev-backend
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-dev-backend
type: Opaque
stringData:
  addr: 'http://vault.vault-dev'
  token: 'some-token'
